#pragma once

#define DISPLAY_COLOR_MOD_ACTIVE       0xb1e5f0
#define DISPLAY_COLOR_MOD_INACTIVE     0x3b527c
#define DISPLAY_COLOR_MOD_SEPARATOR    0x606060
#define DISPLAY_COLOR_MOD_CAPS_WORD    0xffbf00

// WPM waveform: Sith / dark-side red lightsaber.
#define DISPLAY_COLOR_WPM_BAR_ACTIVE   0xcc221d
#define DISPLAY_COLOR_WPM_BAR_INACTIVE 0x242424
#define DISPLAY_COLOR_WPM_TEXT         0xcc221d

#define DISPLAY_COLOR_LAYER_TEXT       0xffffff
#define DISPLAY_COLOR_LAYER_DOT_ACTIVE   0xe0e0e0
#define DISPLAY_COLOR_LAYER_DOT_INACTIVE 0x575757

// Battery level: Luke Skywalker (ROTJ) green lightsaber.
#define DISPLAY_COLOR_BATTERY_FILL     0x33b142
#define DISPLAY_COLOR_BATTERY_RING     0x113b1a
#define DISPLAY_COLOR_BATTERY_BG       0x505050
#define DISPLAY_COLOR_BATTERY_LABEL    0xffffff

#define DISPLAY_COLOR_BATTERY_DISCONNECTED_FILL  0x383c42
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_RING  0x282c30
#define DISPLAY_COLOR_BATTERY_DISCONNECTED_LABEL 0x000000

#define DISPLAY_COLOR_BATTERY_LOW_FILL  0xC08040
#define DISPLAY_COLOR_BATTERY_LOW_RING  0x584028

// USB: Rey Skywalker yellow lightsaber. BLE: Obi-Wan blue lightsaber.
#define DISPLAY_COLOR_USB_ACTIVE_BG        0xcca818
#define DISPLAY_COLOR_USB_INACTIVE_BG      0x4a4216
#define DISPLAY_COLOR_BLE_ACTIVE_BG        0x316fcc
#define DISPLAY_COLOR_BLE_INACTIVE_BG      0x1e293e
#define DISPLAY_COLOR_OUTPUT_ACTIVE_TEXT   0x000000
#define DISPLAY_COLOR_OUTPUT_INACTIVE_TEXT 0x7b7d93

#define DISPLAY_COLOR_SLOT_ACTIVE_BG   0x7b7d93
#define DISPLAY_COLOR_SLOT_INACTIVE_BG 0x353640
#define DISPLAY_COLOR_SLOT_TEXT        0xffffff
